Feature datepicker
deyasix/StandWithUkraine-App pull request #5
Opened 2023-07-27 08:14 UTC by deyasix

I added calendar that opens by click on current date. User can select another date by using calendar. Also I customized it.

2023-07-27 14:02 UTC, okorchysta requested changes
Found a few issues:
1. If you select some future date - date statistic is not changed (it only changes after the screen rotates). Please, check why is this happening. But as a solution - disable future dates in the datepicker
2. If you open datePicker and rotate the screen - datePicker is closed

2023-07-31 09:13 UTC, deyasix commented
I have fixed issues with calendar

2023-07-31 10:49 UTC, okorchysta approved these changes

2023-07-31 10:49 UTC, okorchysta commented on app/src/main/java/com/fivesysdev/standwithukraine/ui/StatisticFragment.kt
> +        minDateCalendar[Calendar.MONTH] = MIN_MONTH - 1
can you use here scope function?

2023-07-31 12:09 UTC, merged